# Generated by Django 4.1.7 on 2023-03-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_taskdescription_task_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='desc',
            new_name='taskDescription',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='taskTitle',
        ),
    ]
